// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnK7pLrR9OEdBJ-OcREM8WHehhHzqFN4s',
    appId: '1:685114492960:web:19d45d4dd92789fb199445',
    messagingSenderId: '685114492960',
    projectId: 'teach-up-9fa50',
    authDomain: 'teach-up-9fa50.firebaseapp.com',
    storageBucket: 'teach-up-9fa50.appspot.com',
    measurementId: 'G-B4N6THHB6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW30kivTCa5SefR5mOgRX1U6yl5KTlLwI',
    appId: '1:685114492960:android:5043752c10797a8d199445',
    messagingSenderId: '685114492960',
    projectId: 'teach-up-9fa50',
    storageBucket: 'teach-up-9fa50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB27dpZd1m14SBwT8iUM_jeXCn8k6RvCg',
    appId: '1:685114492960:ios:203e1309afe18fc0199445',
    messagingSenderId: '685114492960',
    projectId: 'teach-up-9fa50',
    storageBucket: 'teach-up-9fa50.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB27dpZd1m14SBwT8iUM_jeXCn8k6RvCg',
    appId: '1:685114492960:ios:1c5c2981bd85d457199445',
    messagingSenderId: '685114492960',
    projectId: 'teach-up-9fa50',
    storageBucket: 'teach-up-9fa50.appspot.com',
    iosBundleId: 'com.example.learning.RunnerTests',
  );
}
